server:
  port: 9527
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: gateWay1
        uri: lb://PROVIDER
        predicates:
          -  Path=/helloWorld   
          -  After=2020-03-16T11:20:13.994529900+08:00[Asia/Shanghai]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

      
   
      
      
